[general]
import = ["kanagawa_dragon.toml"]

[window]
padding.x = 5
padding.y = 5
opacity = 0.85
startup_mode = "Maximized"

[mouse]
hide_when_typing = true

[font]
size = 14

[font.normal]
family = "Fira Code"

